<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Default Application</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getWebroot(); ?>css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->getWebroot(); ?>css/app.css" />
        <script type="text/javascript" src="<?php echo $this->getWebroot(); ?>js/jquery-1.8.0.js"></script>
        <script type="text/javascript" src="<?php echo $this->getWebroot(); ?>js/bootstrap.js"></script>
        <script type="text/javascript" src="<?php echo $this->getWebroot(); ?>js/app.js"></script>
    </head>

    <body>
        <div class="container">
            <h1>meerkat</h1>
            <?php $this->getContent(); ?>
        </div>
    </body>
</html>